### ISSUE TITLE
error from the runtime

### ISSUE THREAD

**Issue by jjhesk** [qwerty-w/btc-lib#1]
at the line `expected_T, converted_T`

```python
    class TypeConverter[expected_T, converted_T]:  # Descriptor
                       ^
SyntaxError: invalid syntax
```

which python are you running?

**Comment by qwerty-w** [comment]
> at the line `expected_T, converted_T`
> 
> ```python
>     class TypeConverter[expected_T, converted_T]:  # Descriptor
>                        ^
> SyntaxError: invalid syntax
> ```
> 
> which python are you running?

you need to use python3.12 and newer
